version: '2'
services:
  mqtt:
    image: harbor.swms-cloud.com/iot/mosquittodocker:latest
    ports:
      - 1883:1883
      - 8083:8083
      - 8885:8883
      - 8116:80
    env_file:
      - mosquitto.env
    volumes:
      - mosquitto_conf:/mosquitto/config
      - mosquitto_log:/mosquitto/log
      - letsencrypt:/etc/letsencrypt
      - scripts:/scripts
    container_name: mqtt
    hostname: mqtt
    restart: always

volumes:
  mosquitto_conf:
  mosquitto_log:
  letsencrypt:
  scripts:
