version: '2'
services:
  mqtt:
    image: iot/mosquittodockerletsencrypt
#    networks:
#      - mosquitto-net
    ports:
      - 1883:1883
      - 8083:8083
      - 8885:8883
      - 8116:80
    environment:
      - DOMAIN=mqtt.monitoring.profec-ventus.com
      - EMAIL=lewandowski@swms.de
    volumes:
      - mosquitto_conf:/mosquitto/conf
      - mosquitto_log:/mosquitto/log
      - letsencrypt:/etc/letsencrypt
      - scripts:/scripts
    container_name: mqtt
    restart: always
volumes:
  mosquitto_conf:
  mosquitto_log:
  letsencrypt:
  scripts:

#networks:
#  backend-net:
#    external:
#      name: mosquitto-net
